// ─── COMPANY DATA ────────────────────────────────────────────────────────────
const COMPANIES = [
  // ── MIDLANDS / ATHLONE HUB ──────────────────────────────────────────────────
  {
    id: "novo-nordisk-athlone",
    name: "Novo Nordisk",
    type: "pharma",
    hub: "midlands",
    location: "Monksland, Athlone, Co. Westmeath",
    lat: 53.422, lng: -7.942,
    distanceKm: 35, driveMinutes: 30,
    transportScore: 3,
    transportNote: "No direct rail; 30-min drive or Bus Éireann Route 64 from Mullingar to Athlone. Athlone itself is on the Dublin–Galway rail line.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~400",
    sector: "Pharmaceutical Manufacturing",
    tagline: "Global diabetes & obesity therapy leader — major GMP manufacturing base just 35 km from Mullingar",
    description: "Novo Nordisk acquired the former Alkermes Athlone site in May 2024 for $92.5 m, taking on ~400 staff and a 35-acre, 47,000 m² GMP-grade facility. The site manufactures solid oral-dose pharmaceuticals and is being integrated into Novo Nordisk's global supply chain as demand for GLP-1 obesity and diabetes treatments surges. Novo Nordisk is the world's most valuable healthcare company by market cap, making this an exceptionally stable placement host.\n\nThe Monksland facility has decades of pharmaceutical manufacturing history (formerly operated by Élan and then Alkermes) giving it deep institutional knowledge in drug product formulation, Quality Assurance, and regulatory affairs.",
    whyItSuitsUS861: "US861 covers biopharmaceutical processes, GMP manufacturing, QA/QC, microbiology, and analytical science — exactly what Novo Nordisk Athlone operates daily. A placement here would give hands-on experience in cGMP drug product manufacturing, release testing, and the regulatory environment that pharma graduates enter. The proximity (35 km) means no relocation needed, and the global parent company opens doors to future international roles.",
    placementInfo: "Novo Nordisk runs formal summer internship and industrial placement programmes across its Irish sites. Applications typically open in late autumn for the following year. Check the Novo Nordisk Ireland careers portal and LinkedIn. The Athlone site is actively integrating its post-acquisition workforce and is likely to expand student intake.",
    website: "https://www.novonordisk.ie/",
    highlights: ["35 km from Mullingar", "cGMP manufacturing", "World's leading diabetes company", "Fastest-growing big pharma"]
  },
  {
    id: "medtronic-athlone",
    name: "Medtronic (Athlone)",
    type: "medtech",
    hub: "midlands",
    location: "Athlone, Co. Westmeath",
    lat: 53.428, lng: -7.938,
    distanceKm: 38, driveMinutes: 32,
    transportScore: 3,
    transportNote: "35-min drive or bus from Mullingar. Athlone is on the Dublin–Galway rail line.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~500",
    sector: "Medical Devices",
    tagline: "World's largest medical device company, with a significant manufacturing presence minutes from Mullingar",
    description: "Medtronic's Athlone operation (formerly Covidien, acquired 2015) manufactures medical devices and has been a cornerstone of the Westmeath life sciences cluster for decades. Medtronic employs over 4,000 people across five Irish sites with its EMEA headquarters in Galway. The company makes cardiac devices, insulin pumps, surgical instruments, and neuromodulation products.\n\nAs the world's largest standalone medical device company (revenue ~$32 bn), Medtronic offers unparalleled stability, global career pathways, and a culture of innovation underpinned by heavy R&D investment.",
    whyItSuitsUS861: "Biotech graduates from US861 bring direct value to device quality testing, biocompatibility assays, sterility testing, and validation work — all critical in a regulated medical device environment. Medtronic Athlone provides a route into the devices sector without leaving Co. Westmeath.",
    placementInfo: "Medtronic Ireland runs a competitive graduate development programme and takes undergraduate placement students at multiple Irish sites. Contact Medtronic Ireland HR directly and monitor their careers portal and LinkedIn Ireland page. University liaison programmes are common at the Galway and Athlone sites.",
    website: "https://www.medtronic.com/ie-en/",
    highlights: ["~38 km from Mullingar", "World's largest med-device company", "Strong QA/validation roles"]
  },
  {
    id: "jnj-athlone",
    name: "Johnson & Johnson (Athlone)",
    type: "pharma",
    hub: "midlands",
    location: "Athlone, Co. Westmeath",
    lat: 53.430, lng: -7.945,
    distanceKm: 38, driveMinutes: 32,
    transportScore: 3,
    transportNote: "35-min drive or bus from Mullingar.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~300",
    sector: "Biopharmaceutical Manufacturing",
    tagline: "Aseptic fill-finish biologics manufacturing — one of J&J's most advanced Irish sites, 35 km away",
    description: "Johnson & Johnson's Athlone facility specialises in aseptic fill-finish manufacturing and is expanding into biologics production. J&J employs over 5,000 people across ten Irish locations and has been investing in Ireland for over 50 years. The Athlone site operates to the highest sterile manufacturing standards, making drug product for global distribution.\n\nJ&J (now operating its pharma division as Janssen) has one of the most comprehensive graduate development programmes in Irish pharma, with structured rotations, mentoring, and international mobility.",
    whyItSuitsUS861: "Aseptic processing, sterility assurance, cell culture, upstream/downstream biologics — all core to US861 — are the daily currency of this site. A placement here would give direct industry experience in biologics manufacturing at one of the world's most prestigious pharma companies. Incredibly accessible from Mullingar.",
    placementInfo: "J&J Ireland runs formal placement and graduate programmes. Applications open typically September–November for the following summer/year. Visit jnj.com/careers and search Ireland. The Athlone site actively participates in TUS Midlands placement partnerships.",
    website: "https://www.jnj.com/latest-news/johnson-johnson-ireland",
    highlights: ["~38 km from Mullingar", "Biologics fill-finish", "Top graduate programme", "TUS Midlands partnership"]
  },
  {
    id: "alexion-athlone",
    name: "Alexion / AstraZeneca (Athlone)",
    type: "biotech",
    hub: "midlands",
    location: "Athlone, Co. Westmeath",
    lat: 53.425, lng: -7.950,
    distanceKm: 40, driveMinutes: 33,
    transportScore: 3,
    transportNote: "35-min drive or bus from Mullingar.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 3,
    careerDevScore: 5,
    employees: "~200",
    sector: "Rare Disease Biologics",
    tagline: "Cutting-edge rare-disease drug substance production — AstraZeneca subsidiary, minutes from home",
    description: "Alexion Pharmaceuticals, acquired by AstraZeneca in 2021 for $39 bn, operates drug substance production facilities in Athlone focused on ultra-rare disease biologics (complement inhibitors like Soliris and Ultomiris). These are complex, high-value biologic medicines requiring state-of-the-art upstream and downstream bioprocessing.\n\nBeing part of AstraZeneca, one of the world's top five biopharma companies, gives access to extensive global networks, learning academies, and career development across oncology, rare disease, and respiratory franchises.",
    whyItSuitsUS861: "This is perhaps the most scientifically exciting placement close to Mullingar for a biotechnology student. Rare-disease biologics production directly applies cell culture, protein purification, analytical biochemistry, and QA/QC knowledge from US861. The upstream/downstream processing at Alexion mirrors what students study in biopharmaceutical process modules.",
    placementInfo: "AstraZeneca Ireland (via Alexion) runs student placement and graduate programmes. Monitor the AstraZeneca Early Talent portal. Applications are competitive — a strong academic record and lab skills are key differentiators.",
    website: "https://www.astrazeneca.ie/",
    highlights: ["~40 km from Mullingar", "Rare disease biologics", "Part of AstraZeneca", "Upstream/downstream bioprocessing"]
  },

  // ── DUBLIN HUB ─────────────────────────────────────────────────────────────
  {
    id: "pfizer-dublin",
    name: "Pfizer (Dublin)",
    type: "pharma",
    hub: "dublin",
    location: "Grange Castle, Dublin 22",
    lat: 53.318, lng: -6.435,
    distanceKm: 85, driveMinutes: 70,
    transportScore: 5,
    transportNote: "Direct Irish Rail train Mullingar → Dublin Connolly (~1 hr). Then Luas Red Line or bus to Grange Castle. Excellent public transport.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~4,000 (Ireland total)",
    sector: "Biopharmaceutical Manufacturing",
    tagline: "World's largest pharma company — one of Ireland's biggest employers with top-tier graduate programmes",
    description: "Pfizer is Ireland's largest exporter and employs ~4,000 people across seven Irish sites. The Grange Castle site in Dublin is a world-scale biopharmaceutical campus manufacturing monoclonal antibodies, vaccines, and sterile injectables. Pfizer invested heavily in Ireland during COVID-19 vaccine production and continues major capital investment.\n\nPfizer's Irish graduate programme (23-month initial contract) is among the most sought-after in the country, offering structured development across manufacturing, engineering, quality, and regulatory functions.",
    whyItSuitsUS861: "Every module in US861 maps to a Pfizer role: microbiology (environmental monitoring), cell culture (upstream manufacturing), analytical chemistry (QC labs), process engineering (tech transfer), QA (document control, GMP compliance). A Pfizer placement is a golden line on a CV and frequently leads to a graduate job.",
    placementInfo: "Pfizer Ireland runs both summer internship (June–August) and year-long industrial placement programmes. Applications open in October/November for the following year. Visit pfizer.ie/career. Strong bias toward students from Irish science degrees — US861 is highly competitive for these roles.",
    website: "https://www.pfizer.ie/career/graduate-programme/",
    highlights: ["Direct train from Mullingar", "World's #1 pharma", "23-month graduate programme", "All US861 modules applicable"]
  },
  {
    id: "msd-dublin",
    name: "MSD Ireland (Merck)",
    type: "pharma",
    hub: "dublin",
    location: "Swords, Co. Dublin",
    lat: 53.460, lng: -6.219,
    distanceKm: 100, driveMinutes: 80,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + Bus Éireann/Dublin Bus to Swords. Total ~1.5 hrs.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~2,500 (Ireland)",
    sector: "Pharmaceutical Manufacturing & R&D",
    tagline: "Merck's European hub — biologics, API, and vaccine manufacturing with one of Ireland's best grad schemes",
    description: "MSD (Merck Sharp & Dohme) has been in Ireland since 1976 and is one of the largest pharma employers in the country across sites in Dublin, Cork (Brinny, Carlow). The Irish operations manufacture biologics, APIs, and vaccines including Keytruda (the world's best-selling cancer drug). MSD Ireland actively recruits September graduates across manufacturing sciences, QA, regulatory, and engineering.\n\nMSD's graduate development programme involves interdepartmental rotations with senior mentorship — applications open September 2025 for 2026 intake.",
    whyItSuitsUS861: "Keytruda is a monoclonal antibody — the same class of biologic covered in US861 biopharmaceutical modules. QA, GMP, microbiology, and analytical sciences roles are entry points for US861 graduates. MSD's graduate programme is explicitly designed to take science graduates from Irish universities.",
    placementInfo: "MSD Ireland runs a formal graduate programme (open September each year) and an internship programme. Visit jobs.msd.com and search 'Ireland student'. Athlone/TUS students have historically placed at MSD Cork and Dublin sites.",
    website: "https://www.msd.ie/careers/",
    highlights: ["Train from Mullingar", "Keytruda biologics", "Sept 2025 grad programme open", "Rotational grad scheme"]
  },
  {
    id: "bms-dublin",
    name: "Bristol Myers Squibb",
    type: "biotech",
    hub: "dublin",
    location: "Cruiserath, Dublin 15",
    lat: 53.392, lng: -6.378,
    distanceKm: 82, driveMinutes: 68,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + bus to Cruiserath (~1.5 hrs total). Site is accessible from Dublin city centre.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~600",
    sector: "Biologics Manufacturing",
    tagline: "State-of-the-art biologics campus — BMS's largest manufacturing site outside the USA",
    description: "Bristol Myers Squibb's Cruiserath facility is a €1.3 bn biologics campus and BMS's largest manufacturing site outside the United States. It produces Opdivo (nivolumab) — an immuno-oncology monoclonal antibody — and represents some of the most advanced biologic manufacturing technology in the world.\n\nBMS in Ireland is known for a strong employee culture, significant investment in staff development, and active participation in college placement programmes.",
    whyItSuitsUS861: "Monoclonal antibody production (upstream cell culture, downstream purification, formulation, fill-finish) is the curriculum of US861 biopharmaceutical modules made real. Cruiserath operates exactly these processes at commercial scale. A BMS placement is a pinnacle experience for a biotech graduate.",
    placementInfo: "BMS Ireland offers placement and graduate roles. Monitor bms.com/careers and BMS Ireland LinkedIn. The Cruiserath site has taken TUS/AIT students on placement historically.",
    website: "https://www.bms.com/about-us/our-company/operations/bms-cruiserath-biologics.html",
    highlights: ["Direct train + bus from Mullingar", "World-scale biologics", "Opdivo mAb production", "BMS's flagship EU site"]
  },
  {
    id: "abbvie-dublin",
    name: "AbbVie (Dublin)",
    type: "pharma",
    hub: "dublin",
    location: "Swords, Co. Dublin",
    lat: 53.462, lng: -6.221,
    distanceKm: 100, driveMinutes: 80,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + bus to Swords. ~1.5 hrs total.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~1,500 (Ireland)",
    sector: "Biopharmaceutical Manufacturing",
    tagline: "Makers of Humira and Skyrizi — AbbVie's Irish biologics hub with strong graduate pathways",
    description: "AbbVie has been in Ireland since 1980 and employs ~1,500 people across sites in Dublin and Cork. The Irish operations are central to manufacturing Humira (the world's best-selling drug for over a decade) and its successors Skyrizi and Rinvoq. AbbVie invests heavily in employee development and has won multiple awards for being a great place to work in Ireland.\n\nAbbVie's Irish sites span drug product manufacturing, API production, and clinical supply, giving placement students exposure to the full pharmaceutical supply chain.",
    whyItSuitsUS861: "Immunology biologics (antibodies, JAK inhibitors) are directly relevant to the biopharmaceutical manufacturing and analytical chemistry modules in US861. AbbVie's quality-first culture makes it an excellent training ground for the GMP mindset that biotech employers seek.",
    placementInfo: "AbbVie Ireland runs internship and co-op placement programmes. Applications through abbvie.com/careers. The Dublin (Swords) site is the primary placement destination. Apply September–November for summer/annual placements.",
    website: "https://www.abbvie.ie/",
    highlights: ["Train from Mullingar", "Humira/Skyrizi biologics", "Multi-year Irish presence", "Great employer awards"]
  },
  {
    id: "icon-plc",
    name: "ICON Plc",
    type: "cro",
    hub: "dublin",
    location: "Leopardstown, Dublin 18",
    lat: 53.274, lng: -6.213,
    distanceKm: 100, driveMinutes: 85,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + DART/Luas to Leopardstown. ~1.5 hrs total.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~6,000 (Ireland HQ)",
    sector: "Contract Research Organisation",
    tagline: "Ireland's largest CRO and one of the world's biggest — renowned for taking life science graduates",
    description: "ICON Plc is an Irish-headquartered global contract research organisation (CRO) with over 41,000 employees worldwide and revenues exceeding $8 bn. They run clinical trials across every therapeutic area for most of the world's top pharma companies. ICON is consistently listed as one of the best graduate employers in Ireland and runs one of the largest structured graduate programmes in life sciences.\n\nICON offers placements and graduate roles across clinical data management, biostatistics, regulatory affairs, pharmacovigilance, clinical operations, and laboratory sciences.",
    whyItSuitsUS861: "The analytical and scientific foundations of US861 (biochemistry, microbiology, data analysis) translate into roles in bioanalytical laboratory work, clinical data review, and regulatory science at ICON. CRO experience gives a breadth of therapeutic area exposure that in-house pharma cannot match — excellent for early career development.",
    placementInfo: "ICON runs a large, well-structured internship and graduate programme. Apply at iconplc.com/careers. Applications open all year for various cohorts. ICON is one of the most accessible large employers for Irish science graduates — very placement-student friendly.",
    website: "https://www.iconplc.com/careers/",
    highlights: ["Train from Mullingar", "World's leading CRO", "Largest Irish grad programme", "Diverse therapeutic exposure"]
  },
  {
    id: "takeda-dublin",
    name: "Takeda Pharmaceuticals",
    type: "pharma",
    hub: "dublin",
    location: "Grange Castle / Bray, Co. Wicklow",
    lat: 53.200, lng: -6.099,
    distanceKm: 115, driveMinutes: 90,
    transportScore: 4,
    transportNote: "Train to Dublin Connolly + DART to Bray (~1.5–2 hrs). Grange Castle accessible by Dublin Bus.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~2,500 (Ireland)",
    sector: "Biopharmaceutical Manufacturing",
    tagline: "Japan's largest pharma company — a world leader in rare disease biologics with a major Irish base",
    description: "Takeda is one of the world's top ten pharmaceutical companies and has been in Ireland since 1997. Its Irish operations focus on plasma-derived therapies, biologics manufacturing, and solid dose pharmaceuticals across sites in Dublin and Wicklow. The Grange Castle site is a €500 m biologics campus. Takeda is known for a collaborative culture and invests significantly in employee development.\n\nTakeda's focus on rare diseases, oncology, and neuroscience makes it one of the most scientifically interesting employers in Ireland.",
    whyItSuitsUS861: "Plasma fractionation, recombinant protein manufacturing, and downstream purification at Takeda are direct extensions of the upstream/downstream bioprocessing content in US861. Their rare disease focus adds clinical context that distinguishes a Takeda CV from generic manufacturing experience.",
    placementInfo: "Takeda Ireland runs internship and graduate programmes. Apply at takeda.com/en-ie/careers/. The Irish Early Talent team is active on LinkedIn Ireland. Apply by December for summer placements.",
    website: "https://www.takeda.com/en-ie/",
    highlights: ["Good transport from Mullingar", "Plasma-derived biologics", "Rare disease focus", "Top 10 global pharma"]
  },
  {
    id: "novartis-dublin",
    name: "Novartis Ireland",
    type: "pharma",
    hub: "dublin",
    location: "Citywest, Dublin 24",
    lat: 53.283, lng: -6.382,
    distanceKm: 90, driveMinutes: 72,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + Luas Red Line to Citywest. ~1.5 hrs total.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~800 (Ireland)",
    sector: "Pharmaceutical & Cell Therapy",
    tagline: "Pioneer of CAR-T cell therapy (Kymriah) — one of pharma's most innovative companies",
    description: "Novartis in Ireland employs ~800 people at Citywest, Dublin, including medical affairs, commercial, and manufacturing functions. Novartis is the company behind Kymriah — the world's first approved CAR-T cell therapy — and invests more in R&D as a percentage of revenue than almost any other company. Their Irish operations also support gene therapy and advanced cell therapy development.\n\nNovartis was ranked the #1 pharmaceutical employer globally by Science in 2023.",
    whyItSuitsUS861: "CAR-T cell therapy is the frontier of biotechnology, and Novartis's Irish presence provides a window into cell-based manufacturing that is highly relevant to the cell biology and biopharmaceutical modules of US861. Even commercial/medical science roles give exposure to cutting-edge therapy areas.",
    placementInfo: "Novartis Ireland runs internship and graduate programmes with a focus on STEM graduates. Apply at novartis.ie/careers. Their Future Talent programme accepts science undergraduates.",
    website: "https://www.novartis.ie/",
    highlights: ["Train + Luas from Mullingar", "CAR-T cell therapy pioneers", "#1 pharma employer (Science)", "Gene therapy growth area"]
  },
  {
    id: "amgen-dublin",
    name: "Amgen Ireland",
    type: "biotech",
    hub: "dublin",
    location: "Dun Laoghaire, Co. Dublin",
    lat: 53.295, lng: -6.131,
    distanceKm: 107, driveMinutes: 85,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + DART to Dun Laoghaire (~1.5 hrs). Direct DART connection.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 3,
    careerDevScore: 5,
    employees: "~200 (Dublin)",
    sector: "Biotechnology R&D & Commercial",
    tagline: "One of the world's founding biotech companies — strong scientific culture in Dublin",
    description: "Amgen pioneered the biotechnology industry and has been in Ireland since 2003. The Dublin office houses commercial, medical, and regulatory functions, though Amgen's main manufacturing presence is international. Amgen is famous for its scientific culture, its biologics portfolio (Enbrel, Prolia, Repatha), and increasingly its biosimilars and obesity pipeline.\n\nAmgen's BRAINS (Building Relationships and Inspiring New Scientists) programme engages with Irish universities and placement students.",
    whyItSuitsUS861: "Amgen's biological medicines (monoclonal antibodies, erythropoietins, RANKL inhibitors) span the biopharmaceutical content of US861. Even in commercial/medical roles, deep product knowledge gives graduates a scientific edge.",
    placementInfo: "Amgen Ireland takes a smaller number of placements compared to manufacturing-heavy companies. Monitor amgen.com/careers for early talent openings in Ireland.",
    website: "https://www.amgen.ie/",
    highlights: ["DART from Mullingar via Dublin", "Founding biotech company", "Strong scientific culture", "Biosimilars growth area"]
  },
  {
    id: "baxter-kildare",
    name: "Baxter International",
    type: "pharma",
    hub: "dublin",
    location: "Newbridge, Co. Kildare",
    lat: 53.181, lng: -6.800,
    distanceKm: 82, driveMinutes: 65,
    transportScore: 4,
    transportNote: "Train to Dublin Connolly, then train to Newbridge (Kildare line) ~1.5 hrs total. Good rail connection.",
    viabilityScore: 4,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 4,
    employees: "~1,000 (Newbridge)",
    sector: "Pharmaceutical & Medical Products",
    tagline: "IV fluids and hospital nutrition manufacturing — a major employer accessible by rail from Mullingar",
    description: "Baxter International's Newbridge, Co. Kildare site is one of the largest IV solutions manufacturing facilities in Europe, producing intravenous fluids, nutritional products, and renal therapies. The site has been operating in Ireland for over 50 years and is one of the most accessible large pharma employers to Mullingar — connected by rail via Dublin.\n\nBaxter employs over 1,000 people at Newbridge and is known for strong workforce development and apprenticeship-style industrial placements.",
    whyItSuitsUS861: "Sterile manufacturing, aseptic processing, microbiology (sterility testing), and analytical chemistry are core to Baxter's Newbridge operations and directly map to US861 modules. IV solution manufacturing is less glamorous than biologics but offers excellent foundational GMP training.",
    placementInfo: "Baxter Newbridge takes undergraduate placement students through Irish university networks. Contact their HR team directly or apply through baxter.com/careers. Historically has partnered with Irish IT/university systems.",
    website: "https://www.baxter.com/",
    highlights: ["Rail from Mullingar via Dublin", "50+ year Irish presence", "Sterile IV manufacturing", "Strong placement culture"]
  },
  {
    id: "wuxi-biologics",
    name: "WuXi Biologics",
    type: "cdmo",
    hub: "dublin",
    location: "Dundalk, Co. Louth",
    lat: 54.000, lng: -6.405,
    distanceKm: 145, driveMinutes: 105,
    transportScore: 4,
    transportNote: "Train from Mullingar to Dublin (~1 hr) + Enterprise train to Dundalk (~45 min). Good rail connection overall.",
    viabilityScore: 4,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 4,
    employees: "~500 (Dundalk)",
    sector: "Contract Development & Manufacturing",
    tagline: "Fastest-growing CDMO in the world — cutting-edge biologics manufacturing at its new Dundalk facility",
    description: "WuXi Biologics opened its Dundalk facility in 2022 — one of the most advanced single-use biologics manufacturing facilities in Europe. As a CDMO (Contract Development and Manufacturing Organisation), WuXi produces biological medicines for dozens of pharma and biotech clients, giving employees exposure to a diverse range of molecules and processes.\n\nWuXi Biologics is growing extremely rapidly, making it an exciting early-career environment with strong advancement potential.",
    whyItSuitsUS861: "CDMO work is the most technically varied biopharmaceutical experience possible — a student at WuXi Biologics could work on multiple different molecules using the full range of upstream/downstream bioprocessing techniques covered in US861. Highly relevant and strongly recommended.",
    placementInfo: "WuXi Biologics Ireland runs placement and graduate programmes at the Dundalk site. Apply via wuxibiologics.com/careers or LinkedIn. The facility is still building its team, making this a good time to build connections.",
    website: "https://www.wuxibiologics.com/",
    highlights: ["Train from Mullingar via Dublin", "World's fastest-growing CDMO", "Single-use biologics", "Huge diversity of projects"]
  },
  {
    id: "iqvia-dublin",
    name: "IQVIA (Ireland)",
    type: "cro",
    hub: "dublin",
    location: "Leopardstown, Dublin 18",
    lat: 53.277, lng: -6.212,
    distanceKm: 100, driveMinutes: 85,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + DART/Luas to Leopardstown (~1.5 hrs).",
    viabilityScore: 5,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 4,
    careerDevScore: 4,
    employees: "~1,500 (Ireland)",
    sector: "Data-Driven Clinical Research",
    tagline: "World's largest healthcare data and CRO company — a strong alternative to traditional pharma placements",
    description: "IQVIA (formerly Quintiles and IMS Health) is the world's largest CRO and healthcare intelligence company, employing ~85,000 globally. The Dublin hub handles clinical trial management, real-world evidence, biostatistics, and technology services for pharma clients worldwide. IQVIA is strong on data science and digital health — an emerging growth area for life science graduates.\n\nIQVIA offers a route into life sciences that is less lab-focused and more data, regulatory, and operations oriented.",
    whyItSuitsUS861: "US861's scientific foundation opens doors to clinical data management, biostatistics support, and regulatory submissions at IQVIA. Less direct than manufacturing but offers excellent transferable skills, global exposure, and strong graduate development.",
    placementInfo: "IQVIA Ireland runs a well-known graduate programme. Apply at iqvia.com/careers. Strong recommendation for students interested in the commercial/regulatory/data side of pharma rather than lab-based manufacturing.",
    website: "https://www.iqvia.com/careers",
    highlights: ["Train from Mullingar", "World's largest healthcare data co", "Digital health growth", "Clinical trial management"]
  },
  {
    id: "jazz-pharma",
    name: "Jazz Pharmaceuticals",
    type: "pharma",
    hub: "dublin",
    location: "Sandyford, Dublin 18",
    lat: 53.272, lng: -6.207,
    distanceKm: 102, driveMinutes: 85,
    transportScore: 5,
    transportNote: "Train to Dublin Connolly + Luas Green Line to Sandyford (~1.5 hrs).",
    viabilityScore: 4,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 3,
    careerDevScore: 4,
    employees: "~300 (Dublin HQ)",
    sector: "Specialty Pharmaceuticals",
    tagline: "Irish-headquartered specialty pharma focused on sleep & oncology — good for regulatory/commercial experience",
    description: "Jazz Pharmaceuticals is a biopharmaceutical company headquartered in Dublin (Irish-domiciled since 2012) focused on neuroscience and oncology. Products include Xyrem (sodium oxybate) for narcolepsy and Vyxeos for acute myeloid leukaemia. The Dublin HQ houses corporate functions, medical affairs, and regulatory teams.\n\nAs a mid-sized speciality company, Jazz offers the benefits of a focused scientific environment with access to broad functional experience across a smaller, more connected team.",
    whyItSuitsUS861: "Jazz's oncology biologics pipeline creates roles in regulatory science, pharmacovigilance, and medical science liaison work that suit scientifically trained graduates. Less manufacturing-focused than other Dublin employers.",
    placementInfo: "Jazz Pharmaceuticals Dublin takes a small number of placement students and graduate hires. Monitor jazzpharma.com/careers and LinkedIn. Good fit for students interested in regulatory affairs or medical science.",
    website: "https://www.jazzpharma.com/",
    highlights: ["Luas from Dublin Connolly", "Irish-HQ company", "Oncology & neuroscience focus", "Regulatory/medical roles"]
  },

  // ── GALWAY HUB ─────────────────────────────────────────────────────────────
  {
    id: "medtronic-galway",
    name: "Medtronic (Galway EMEA HQ)",
    type: "medtech",
    hub: "galway",
    location: "Parkmore, Galway",
    lat: 53.274, lng: -8.987,
    distanceKm: 117, driveMinutes: 88,
    transportScore: 3,
    transportNote: "Bus Éireann Expressway 20X Dublin–Galway stops in Mullingar area (~2 hrs to Galway). Or drive. No direct train.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~4,000 (Galway)",
    sector: "Medical Devices",
    tagline: "Medtronic's European nerve centre — 4,000 staff, world-leading cardiac and surgical device innovation",
    description: "Medtronic's Galway campus is its EMEA headquarters and houses R&D, manufacturing, and corporate functions for cardiac rhythm management, neuromodulation, and surgical robotics. With 4,000+ employees across five Galway sites, Medtronic is the single largest employer in Galway city and the cornerstone of its world-famous medtech cluster.\n\nMedtronic Galway spends over €400 m annually in Ireland, has on-site innovation labs, and offers structured graduate rotational programmes. The engineering-science interface makes it a strong landing zone for biotech graduates moving toward medical technology.",
    whyItSuitsUS861: "Biocompatibility testing, sterility assurance, validation, quality systems, and analytical testing all draw on US861's biotech curriculum. Medtronic Galway also operates R&D labs that use cellular and biological assay techniques. One of the best medtech experiences available.",
    placementInfo: "Medtronic Ireland runs a competitive graduate programme. Apply at medtronic.com/ie-en/about/careers. The Galway campus has strong links to NUI Galway and actively takes placement students from Irish biotech and engineering programmes.",
    website: "https://www.medtronic.com/ie-en/",
    highlights: ["Galway medtech hub HQ", "4,000+ employees in Galway", "R&D + manufacturing", "Cardiac & surgical devices"]
  },
  {
    id: "boston-scientific-galway",
    name: "Boston Scientific (Galway)",
    type: "medtech",
    hub: "galway",
    location: "Ballybrit, Galway",
    lat: 53.286, lng: -8.980,
    distanceKm: 118, driveMinutes: 88,
    transportScore: 3,
    transportNote: "Bus Éireann Expressway or drive. Galway ~2 hrs by express bus from Mullingar.",
    viabilityScore: 5,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~5,000 (Ireland)",
    sector: "Medical Devices",
    tagline: "€75 m R&D investment in Galway — a world hub for electrophysiology and cardiac device innovation",
    description: "Boston Scientific employs ~5,000 people across sites in Galway, Cork, and Clonmel, making it one of Ireland's largest medtech employers. The Galway campus recently received a €75 m R&D investment and is a global centre for electrophysiology, neuromodulation, and urology product development and manufacturing.\n\nBoston Scientific is known for a strong innovation culture, significant R&D investment, and excellent career development for engineering and science graduates.",
    whyItSuitsUS861: "Device biocompatibility, in vitro testing, quality control/assurance, and validation activities at BSC Galway utilise biotech graduates' lab and analytical skills. Less cell-biology heavy than pharma, but an excellent introduction to the medtech regulatory environment (ISO 13485, FDA 21 CFR Part 820).",
    placementInfo: "Boston Scientific Ireland runs placement and graduate programmes. Apply at bostonscientific.com/en-US/careers. The Galway site has strong college links and regularly takes placement students from science programmes.",
    website: "https://www.bostonscientific.com/",
    highlights: ["Galway medtech cluster", "€75m R&D investment", "~5,000 Irish employees", "Electrophysiology innovation"]
  },
  {
    id: "abbott-galway",
    name: "Abbott (Galway)",
    type: "medtech",
    hub: "galway",
    location: "Galway City",
    lat: 53.280, lng: -8.990,
    distanceKm: 119, driveMinutes: 89,
    transportScore: 3,
    transportNote: "Bus Éireann Expressway or drive ~2 hrs.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~3,000 (Ireland)",
    sector: "Diagnostics & Medical Devices",
    tagline: "Makers of life-changing diagnostics — Abbott's Irish hub spans Galway, Sligo, and Longford",
    description: "Abbott Ireland employs ~3,000 people across sites in Galway, Sligo, Clonmel, and Longford. The company is a global leader in diagnostics (Alinity, i-STAT), diabetes care (Libre CGM), cardiovascular devices, and rapid testing. Abbott's Galway site focuses on diagnostic instruments and reagents, while Sligo makes sensors and structural heart products.\n\nAbbott won the best company to work for in Ireland multiple times and is known for active graduate development and career progression.",
    whyItSuitsUS861: "Diagnostics reagent manufacturing, immunoassay development, molecular biology, and analytical science are core to Abbott's Galway operations and directly relevant to US861's microbiology and analytical chemistry content. Diabetes diagnostics (CGM) also involves biochemistry graduates.",
    placementInfo: "Abbott Ireland runs a well-regarded graduate programme and placement scheme. Apply at abbott.com/careers. The Galway and Sligo sites both take placement students.",
    website: "https://www.abbott.ie/",
    highlights: ["Major Irish diagnostics employer", "Galway + Sligo sites", "CGM diabetes tech leader", "Best employer awards"]
  },

  // ── LIMERICK / SHANNON HUB ─────────────────────────────────────────────────
  {
    id: "regeneron-limerick",
    name: "Regeneron",
    type: "biotech",
    hub: "limerick",
    location: "Raheen Business Park, Limerick",
    lat: 52.627, lng: -8.634,
    distanceKm: 149, driveMinutes: 105,
    transportScore: 2,
    transportNote: "Bus Éireann from Mullingar to Athlone then Limerick ~3 hrs. Driving strongly recommended.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~1,400 (Limerick)",
    sector: "Biologics Manufacturing",
    tagline: "Ireland's largest bulk biologics facility — Regeneron's €1 bn Irish investment and 1,400+ jobs",
    description: "Regeneron's Limerick facility is the largest bulk biologics manufacturing facility in Ireland and one of the largest in the world. With over $1 bn invested and 1,400+ employees, it produces monoclonal antibodies including Dupixent (the world's best-selling biologic) and Eylea. A further 400 jobs are being added as production scales up.\n\nRegenerons Limerick plant operates at the absolute frontier of biologic manufacturing — large-scale mammalian cell culture, protein purification, and fill-finish — making it one of the most desirable science workplaces in the country.",
    whyItSuitsUS861: "This is the holy grail for a US861 biotechnology student. Everything covered in the biopharmaceutical manufacturing modules — Chinese Hamster Ovary (CHO) cell culture, protein A chromatography, viral filtration, ultrafiltration/diafiltration — happens at Regeneron Limerick daily, at commercial scale. Highly, highly recommended.",
    placementInfo: "Regeneron Limerick runs placement and graduate programmes. Apply at regeneron.com/careers. Given the rapid site expansion, early talent intake is growing. Strong bias toward biotech/biochemical engineering graduates — US861 is ideal.",
    website: "https://www.regeneron.com/locations/ireland",
    highlights: ["World-scale biologics", "Dupixent mAb production", "€1bn investment", "Perfect match for US861"]
  },
  {
    id: "stryker-limerick",
    name: "Stryker (Limerick)",
    type: "medtech",
    hub: "limerick",
    location: "Anngrove, Carrigtwohill (Co. Cork) / Limerick",
    lat: 52.634, lng: -8.630,
    distanceKm: 151, driveMinutes: 107,
    transportScore: 2,
    transportNote: "Long bus journey (~3 hrs). Driving recommended.",
    viabilityScore: 5,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~4,000 (Ireland)",
    sector: "Orthopaedic Medical Devices",
    tagline: "World leader in orthopaedics — Stryker's Irish manufacturing and R&D operations span Cork and Limerick",
    description: "Stryker is the world's leading orthopaedic company and employs ~4,000 people in Ireland across sites in Cork (Carrigtwohill), Limerick, and Tullamore. Products include joint replacements, surgical robotics (MAKO), spine, and neurotechnology. Stryker is consistently ranked one of the best companies to work for globally and is known for strong career development.\n\nIreland is central to Stryker's global manufacturing and R&D strategy, and the company continues to invest significantly.",
    whyItSuitsUS861: "Biocompatibility testing, quality engineering, and validation in an orthopaedic context are entry points for biotech graduates. Less direct than pharma but Stryker offers excellent engineering science exposure.",
    placementInfo: "Stryker Ireland runs placement and graduate programmes with a strong STEM focus. Apply at stryker.com/ie/en/careers. The Anngrove and Limerick sites take placement students.",
    website: "https://www.stryker.com/ie/en/about/careers/",
    highlights: ["World's #1 orthopaedics co", "MAKO surgical robotics", "~4,000 Irish employees", "Top global employer awards"]
  },
  {
    id: "cook-medical",
    name: "Cook Medical (Limerick)",
    type: "medtech",
    hub: "limerick",
    location: "Limerick City",
    lat: 52.661, lng: -8.629,
    distanceKm: 147, driveMinutes: 103,
    transportScore: 2,
    transportNote: "Long bus journey. Driving recommended.",
    viabilityScore: 4,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 3,
    careerDevScore: 3,
    employees: "~500 (Limerick)",
    sector: "Minimally Invasive Medical Devices",
    tagline: "Family-owned global medtech leader — Limerick manufacturing for minimally invasive surgery",
    description: "Cook Medical is one of the world's largest family-owned medical device companies, with a Limerick site manufacturing products for minimally invasive surgery, endoscopy, and vascular intervention. Cook has been in Ireland for decades and is known for a stable, employee-focused culture that differs from publicly traded corporations.\n\nProducts include guidewires, catheters, stents, and biopsy tools used in hospitals worldwide.",
    whyItSuitsUS861: "Biocompatibility, sterility testing, and quality assurance roles are the main entry points for biotechnology graduates. Less biologically intensive than pharma, but a solid foundational medtech experience.",
    placementInfo: "Cook Medical takes placement students at its Irish sites. Apply directly at cookmedical.com/about/careers. A smaller-scale placement environment may suit students preferring a less corporate experience.",
    website: "https://www.cookmedical.com/",
    highlights: ["Family-owned culture", "Minimally invasive surgery", "Limerick established site"]
  },

  // ── CORK HUB ───────────────────────────────────────────────────────────────
  {
    id: "pfizer-cork",
    name: "Pfizer (Cork)",
    type: "pharma",
    hub: "cork",
    location: "Ringaskiddy, Co. Cork",
    lat: 51.834, lng: -8.311,
    distanceKm: 260, driveMinutes: 165,
    transportScore: 1,
    transportNote: "Train/bus Dublin to Cork (~3 hrs from Mullingar total). Would require relocation to Cork.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~2,000 (Cork)",
    sector: "API & Biopharmaceutical Manufacturing",
    tagline: "Pfizer's Cork campus — API manufacturing, biotech, and sterile fill-finish on an epic scale",
    description: "Pfizer's Ringaskiddy site is one of the world's largest pharmaceutical active ingredient manufacturing sites, producing APIs for Lipitor, Viagra, and multiple biologics. The campus also includes biopharmaceutical and sterile manufacturing operations. Cork is Pfizer's most important Irish site by manufacturing volume.\n\nCork offers the same gold-standard Pfizer graduate programme as Dublin, but in a pharma-industry-saturated city that is excellent for building an industry network.",
    whyItSuitsUS861: "Identical to the Dublin Pfizer entry — full application of US861 curriculum. Cork placement students often have the advantage of a city with higher pharma employment density (J&J, MSD, Lilly, AbbVie all nearby), maximising networking.",
    placementInfo: "Apply via pfizer.ie/career. Cork and Dublin sites share the same graduate programme intake. Note: this placement would require relocating to Cork for the placement period.",
    website: "https://www.pfizer.ie/career/graduate-programme/",
    highlights: ["World-scale API manufacturing", "Requires Cork relocation", "Same grad programme as Dublin site"]
  },
  {
    id: "jnj-cork",
    name: "Johnson & Johnson (Janssen)",
    type: "pharma",
    hub: "cork",
    location: "Little Island, Cork",
    lat: 51.901, lng: -8.347,
    distanceKm: 255, driveMinutes: 162,
    transportScore: 1,
    transportNote: "Train to Dublin + onward to Cork (~3+ hrs). Relocation to Cork recommended.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 5,
    careerDevScore: 5,
    employees: "~2,000 (Cork)",
    sector: "Pharmaceutical Manufacturing",
    tagline: "Janssen Cork — one of the most prestigious pharma placements in Ireland's southern pharma cluster",
    description: "Janssen Sciences Ireland (J&J's pharma arm) at Little Island, Cork is a major API and drug product manufacturing campus. The site produces oncology and immunology medicines and is a centrepiece of Cork's pharmaceutical cluster alongside Pfizer, MSD, Lilly, and AbbVie.\n\nJ&J Cork participates in the same award-winning graduate programme as the Athlone site, with strong scientific development, mentorship, and a clear pathway from placement to graduate employment.",
    whyItSuitsUS861: "API synthesis, drug product manufacturing, analytical QC, and regulatory CMC writing are the functions at J&J Cork most suited to US861 graduates. The Cork pharma cluster makes networking with peers across multiple companies easy.",
    placementInfo: "Apply at jnj.com/careers and search Cork, Ireland. Industrial placements are 12 months typically. Cork positions competitive — start applications in October.",
    website: "https://www.jnj.com/",
    highlights: ["Cork pharma cluster", "Requires relocation", "World-class grad programme", "API + drug product"]
  },
  {
    id: "biomarin-cork",
    name: "BioMarin Pharmaceutical",
    type: "biotech",
    hub: "cork",
    location: "Shanbally, Co. Cork",
    lat: 51.839, lng: -8.301,
    distanceKm: 262, driveMinutes: 168,
    transportScore: 1,
    transportNote: "Long journey — relocation to Cork area required.",
    viabilityScore: 4,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 3,
    careerDevScore: 4,
    employees: "~500 (Cork)",
    sector: "Rare Disease Biotech",
    tagline: "Ultra-rare disease enzyme replacement therapies — sophisticated biotech manufacturing in Cork",
    description: "BioMarin's Shanbally facility manufactures enzyme replacement therapies for ultra-rare genetic diseases (MPS, PKU, Achondroplasia). These are complex biologics produced using mammalian cell culture, with intensive downstream purification and analytical testing requirements. The site is one of the most scientifically specialised pharma manufacturing environments in Ireland.\n\nBioMarin is a mid-size US biotech company with a strong patient-focused mission that resonates with science graduates motivated by making a difference.",
    whyItSuitsUS861: "Enzyme replacement therapy production involves every element of biopharmaceutical manufacturing taught in US861 — cell culture, chromatography, analytical biochemistry, process characterisation. For a student passionate about rare diseases and cutting-edge biotech, BioMarin Cork is exceptional.",
    placementInfo: "BioMarin takes a small number of placement students. Apply at biomarin.com/careers. Cork-based relocation required. Competitive but rewarding.",
    website: "https://www.biomarin.com/",
    highlights: ["Enzyme replacement therapy", "Ultra-rare diseases", "Sophisticated biotech mfg", "Patient-mission driven"]
  },
  {
    id: "eli-lilly-cork",
    name: "Eli Lilly (Kinsale)",
    type: "pharma",
    hub: "cork",
    location: "Dunderrow, Kinsale, Co. Cork",
    lat: 51.704, lng: -8.514,
    distanceKm: 275, driveMinutes: 175,
    transportScore: 1,
    transportNote: "Relocation to Cork area required. Long journey from Mullingar.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 4,
    careerDevScore: 5,
    employees: "~1,500 (Cork)",
    sector: "Pharmaceutical Manufacturing",
    tagline: "Makers of Mounjaro (tirzepatide) — Lilly's €400 m Irish expansion is one of pharma's hottest opportunities",
    description: "Eli Lilly's Kinsale facility is a major API and drug product manufacturing campus with a €400 m expansion underway (300 new jobs) driven by unprecedented demand for their GLP-1 diabetes and obesity products Mounjaro and Zepbound. Lilly's Irish operations are growing faster than almost any other pharma company's.\n\nLilly is known for a strong employee-development culture, competitive compensation, and an exciting pipeline spanning diabetes, oncology, and Alzheimer's disease.",
    whyItSuitsUS861: "The explosive growth of GLP-1 medicines means Lilly Cork is expanding its biologics and small-molecule manufacturing capabilities — precisely the skills covered in US861. The timing makes this an exceptional opportunity: Lilly is hiring at all levels.",
    placementInfo: "Eli Lilly Ireland runs a graduate development programme. Apply at lilly.com/careers and filter by Ireland. Cork (Kinsale) is their primary Irish manufacturing site. Relocation to Cork required.",
    website: "https://www.lilly.ie/",
    highlights: ["Mounjaro/GLP-1 boom", "€400m expansion underway", "300 new roles", "Requires Cork relocation"]
  },

  // ── WATERFORD HUB ──────────────────────────────────────────────────────────
  {
    id: "bausch-lomb",
    name: "Bausch + Lomb (Waterford)",
    type: "medtech",
    hub: "waterford",
    location: "Waterford City",
    lat: 52.261, lng: -7.106,
    distanceKm: 176, driveMinutes: 115,
    transportScore: 2,
    transportNote: "Train to Dublin + bus/train to Waterford (~3 hrs total). Relocation likely needed for daily commute.",
    viabilityScore: 4,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 3,
    careerDevScore: 3,
    employees: "~1,500 (Waterford)",
    sector: "Ophthalmic Medical Devices",
    tagline: "Waterford icon — 70+ year history manufacturing contact lenses and ophthalmic products",
    description: "Bausch + Lomb's Waterford facility has been manufacturing contact lenses and ophthalmic products since 1959, making it one of Ireland's oldest life sciences operations. The site produces contact lenses, IOLs (intraocular lenses), and ophthalmic pharmaceutical products for global markets.\n\nBausch + Lomb is part of a wider life sciences cluster in Waterford that includes Sanofi/Genzyme — Ireland's 'pharma south-east'.",
    whyItSuitsUS861: "Polymer science, quality control, and manufacturing sciences are the primary connections for US861. Less biologically intensive than pharma, but good QA/QC training.",
    placementInfo: "Bausch + Lomb Waterford takes placement students periodically. Apply via bausch.com/careers.",
    website: "https://www.bausch.com/",
    highlights: ["70+ year Irish site", "Contact lens & IOL manufacturing", "Waterford life sciences cluster"]
  },
  {
    id: "sanofi-waterford",
    name: "Sanofi / Genzyme (Waterford)",
    type: "biotech",
    hub: "waterford",
    location: "IDA Business & Technology Park, Waterford",
    lat: 52.248, lng: -7.098,
    distanceKm: 177, driveMinutes: 116,
    transportScore: 2,
    transportNote: "Train to Dublin + onward to Waterford (~3 hrs total). Relocation likely needed.",
    viabilityScore: 5,
    degreeRelevanceScore: 5,
    gradWillingnessScore: 3,
    careerDevScore: 4,
    employees: "~500 (Waterford)",
    sector: "Rare Disease Biologics (Genzyme)",
    tagline: "Genzyme's rare-disease biologics in Waterford — pioneering enzyme replacement therapy since the 1990s",
    description: "Sanofi's Waterford site operates as part of the legacy Genzyme rare-disease biologics heritage. It manufactures enzyme replacement therapies for Gaucher disease, Fabry disease, and MPS, using complex mammalian cell culture and purification processes. Genzyme was a pioneer of enzyme replacement therapy manufacturing — a genuine biotech milestone.\n\nThe site is scientifically sophisticated and represents one of the more niche but highly technically relevant placement opportunities in Ireland for a biotech graduate.",
    whyItSuitsUS861: "Enzyme replacement therapy (ERT) bioprocessing is advanced biopharmaceutical manufacturing — CHO and other mammalian cell lines, extensive downstream purification, high-level analytical characterisation. A Genzyme/Sanofi placement would be a highly distinguished line on a CV for US861 graduates interested in biologics careers.",
    placementInfo: "Sanofi Ireland (Genzyme division) takes placement students. Apply at sanofi.com/en/careers and filter to Ireland/Waterford. Competitive placement with strong scientific depth.",
    website: "https://www.sanofi.ie/",
    highlights: ["Genzyme ERT manufacturing", "Rare disease biologics", "Sophisticated bioprocessing", "Waterford cluster"]
  },
  {
    id: "gsk-dungarvan",
    name: "GSK (Dungarvan)",
    type: "pharma",
    hub: "waterford",
    location: "Dungarvan, Co. Waterford",
    lat: 52.089, lng: -7.624,
    distanceKm: 193, driveMinutes: 122,
    transportScore: 2,
    transportNote: "Long journey. Relocation required.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 4,
    employees: "~800 (Dungarvan)",
    sector: "Pharmaceutical Manufacturing",
    tagline: "GSK's solid-dose and API manufacturing hub in Co. Waterford — quality-first culture",
    description: "GlaxoSmithKline's Dungarvan facility manufactures solid oral dose pharmaceuticals and APIs for GSK's global supply chain. GSK is the UK's largest pharma company and one of the world's top five, with a strong commitment to employee development and an active Irish graduate programme.\n\nGSK Ireland also has a site in Cork and participates in the GSK Future Leaders Programme for science graduates.",
    whyItSuitsUS861: "Pharmaceutical manufacturing, analytical chemistry, QA/QC and regulatory compliance are the core connections to US861. GSK's scale and global training resources make it a strong career launcher.",
    placementInfo: "GSK Ireland runs the Future Leaders Programme for graduates and takes placement students. Apply at gsk.com/en-gb/careers/. Filter to Ireland. Dungarvan and Cork sites both participate.",
    website: "https://www.gsk.com/en-gb/careers/",
    highlights: ["Top 5 global pharma", "Future Leaders Programme", "API + solid dose mfg"]
  },

  // ── OTHER ──────────────────────────────────────────────────────────────────
  {
    id: "abbott-sligo",
    name: "Abbott (Sligo)",
    type: "medtech",
    hub: "other",
    location: "Sligo Town",
    lat: 54.270, lng: -8.477,
    distanceKm: 129, driveMinutes: 92,
    transportScore: 4,
    transportNote: "Direct Irish Rail train Mullingar → Sligo (~1.5 hrs on the Dublin–Sligo line). Excellent public transport option.",
    viabilityScore: 5,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 4,
    careerDevScore: 4,
    employees: "~3,000 (Sligo)",
    sector: "Diagnostics & Cardiac Devices",
    tagline: "Abbott's largest Irish site — cardiac sensors and diagnostics, connected by direct train from Mullingar",
    description: "Abbott's Sligo site is one of the largest medtech manufacturing facilities in Ireland, producing diagnostic instruments, cardiac rhythm management devices, and blood glucose sensors. The facility employs ~3,000 people and is a cornerstone of Sligo's economy.\n\nCritically, Mullingar is connected to Sligo by direct Irish Rail service on the Dublin–Sligo line — making this one of the best public transport options in this guide, no car required.",
    whyItSuitsUS861: "Abbott's Sligo operations in diagnostics (immunoassays, molecular testing) and cardiac sensors draw directly on biochemistry, analytical science, and biotech manufacturing knowledge from US861. A valuable alternative for students wanting to avoid Dublin without owning a car.",
    placementInfo: "Abbott Sligo runs placement and graduate programmes. Apply at abbott.com/careers. The Sligo site is Abbott's flagship Irish manufacturing campus.",
    website: "https://www.abbott.ie/",
    highlights: ["Direct train from Mullingar!", "3,000 employees in Sligo", "Diagnostics + cardiac devices", "No car needed"]
  },
  {
    id: "hollister-mayo",
    name: "Hollister Incorporated",
    type: "medtech",
    hub: "other",
    location: "Ballyhaunis, Co. Mayo",
    lat: 53.765, lng: -8.766,
    distanceKm: 97, driveMinutes: 72,
    transportScore: 2,
    transportNote: "Limited public transport. Car recommended. ~70-min drive from Mullingar.",
    viabilityScore: 4,
    degreeRelevanceScore: 3,
    gradWillingnessScore: 3,
    careerDevScore: 3,
    employees: "~600 (Ballyhaunis)",
    sector: "Stoma & Continence Medical Devices",
    tagline: "Family-owned global medtech — Ballyhaunis manufacturing site a driveable option from Mullingar",
    description: "Hollister Incorporated is a privately held US medical device company specialising in ostomy, continence care, and wound care products. The Ballyhaunis, Co. Mayo site is a major manufacturing hub and one of the larger employers in the Connacht region, with a stable, employee-oriented culture typical of family-owned companies.\n\nAt ~97 km from Mullingar it is a realistic driving commute or short-term relocation.",
    whyItSuitsUS861: "Quality assurance, microbiology testing, validation, and manufacturing sciences are the core connections for US861 graduates. Stoma and wound care products have biocompatibility requirements that bring biotech knowledge to bear.",
    placementInfo: "Hollister takes placement students at its Irish sites. Apply directly at hollister.com/careers.",
    website: "https://www.hollister.com/en/careers",
    highlights: ["~97 km from Mullingar", "Family-owned culture", "Stable, long-established site"]
  },
  {
    id: "chanelle-pharma",
    name: "Chanelle Pharma",
    type: "pharma",
    hub: "other",
    location: "Loughrea, Co. Galway",
    lat: 53.199, lng: -8.565,
    distanceKm: 110, driveMinutes: 78,
    transportScore: 2,
    transportNote: "Limited public transport to Loughrea. Drive ~75 mins from Mullingar.",
    viabilityScore: 3,
    degreeRelevanceScore: 4,
    gradWillingnessScore: 3,
    careerDevScore: 3,
    employees: "~400 (Loughrea)",
    sector: "Generic Pharmaceuticals",
    tagline: "Ireland's largest indigenous pharma company — a hidden gem for biotech placements in the Midlands",
    description: "Chanelle Pharma is Ireland's largest indigenous pharmaceutical company, manufacturing generic medicines and veterinary pharmaceuticals in Loughrea, Co. Galway. The company is family-owned, Irish-led, and exports to over 60 countries. Chanelle has a genuine R&D function including analytical development, formulation science, and regulatory affairs.\n\nAs an Irish-owned company, Chanelle offers a different culture from multinationals — more entrepreneurial, with graduates often taking on broad responsibilities quickly.",
    whyItSuitsUS861: "Generic pharmaceutical manufacturing covers analytical chemistry, formulation development, QA/QC, and regulatory submissions — all relevant to US861. Chanelle is smaller and more agile than multinationals, giving placement students broader hands-on experience.",
    placementInfo: "Chanelle Pharma takes placement students and is actively supportive of ATU/TUS students. Apply directly via chanellepharma.com/careers or contact their HR team at Loughrea.",
    website: "https://www.chanellepharma.com/",
    highlights: ["Ireland's biggest indigenous pharma", "~78 min drive from Mullingar", "Broad hands-on placement roles", "Irish-owned entrepreneurial culture"]
  }
];

// ─── HUB DATA ─────────────────────────────────────────────────────────────────
const HUBS = [
  {
    id: "midlands",
    name: "Midlands / Athlone",
    centLat: 53.425, centLng: -7.944,
    radiusKm: 20,
    color: "#169B62",
    tagline: "Your backyard — world-class pharma 35 km from Mullingar",
    description: "The Athlone/Westmeath corridor is a hidden gem of Irish life sciences. Novo Nordisk, Medtronic, Johnson & Johnson, and Alexion/AstraZeneca all operate significant facilities within 40 km of Mullingar. The region has over 40 years of pharmaceutical and medical device manufacturing history. No relocation needed — these are daily-commute placements.",
    costOfLiving: 2,
    studentCommunity: "TUS Midlands (Athlone) campus is 35 km away — an active life sciences college community. Mullingar town offers affordable living with all amenities.",
    keyEmployers: ["Novo Nordisk", "Medtronic", "Johnson & Johnson", "Alexion/AstraZeneca"],
    whyRelocate: "You don't need to relocate — this hub is home! Perfect for a first placement without uprooting your life. All four companies here are world-class and offer excellent CV value."
  },
  {
    id: "dublin",
    name: "Dublin",
    centLat: 53.340, centLng: -6.260,
    radiusKm: 25,
    color: "#0066CC",
    tagline: "Ireland's pharma capital — 1 hour by train, thousands of opportunities",
    description: "Dublin and its greater area (including Kildare, Wicklow, Dundalk) host the largest concentration of pharma, biotech, and CRO companies in Ireland. It is directly connected to Mullingar by Irish Rail (1 hour). Most major multinational pharma and biotech companies have Irish HQs or major operations here, creating an unparalleled density of placement and graduate opportunities.",
    costOfLiving: 5,
    studentCommunity: "Huge student and young professional community. Vibrant social scene, excellent transport network. Expensive to rent but manageable with a placement salary.",
    keyEmployers: ["Pfizer", "MSD", "Bristol Myers Squibb", "AbbVie", "ICON Plc", "Takeda", "Novartis", "Amgen", "Baxter", "WuXi Biologics"],
    whyRelocate: "Dublin gives access to the densest pharma/biotech job market in Ireland. A Dublin placement puts you in the best position for a graduate job. The train from Mullingar makes it a realistic commute or easy to visit home."
  },
  {
    id: "galway",
    name: "Galway",
    centLat: 53.278, centLng: -8.986,
    radiusKm: 20,
    color: "#8B0000",
    tagline: "Medtech capital of Europe — 4 world leaders in one city",
    description: "Galway is globally recognised as one of the most important medtech hubs in the world. Medtronic, Boston Scientific, and Abbott alone employ over 12,000 people within a few kilometres of each other. The city also hosts NUI Galway (University of Galway), creating a strong life sciences research and student ecosystem. Galway is a vibrant, cultural city renowned for its quality of life.",
    costOfLiving: 4,
    studentCommunity: "University of Galway creates a large, active student community. Excellent bar scene, arts, and outdoor activities. Popular relocation destination for Irish life science graduates.",
    keyEmployers: ["Medtronic (EMEA HQ)", "Boston Scientific", "Abbott", "Integer Medical", "Chanelle Pharma"],
    whyRelocate: "If you're interested in medical devices, Galway is the best place in the world to start your career. The concentration of employers means strong social networks, easy job hopping for career growth, and a city that genuinely loves its medtech community."
  },
  {
    id: "limerick",
    name: "Limerick / Shannon",
    centLat: 52.650, centLng: -8.630,
    radiusKm: 25,
    color: "#FF6B00",
    tagline: "Ireland's fastest-growing life sciences hub — led by Regeneron's €1bn investment",
    description: "Limerick and the Shannon region are experiencing rapid life sciences growth, anchored by Regeneron's world-scale biologics facility, Stryker's orthopaedic operations, and a growing cluster of medical device manufacturers. University of Limerick (UL) is one of Ireland's top engineering and science universities, creating strong local talent pipelines.",
    costOfLiving: 3,
    studentCommunity: "University of Limerick creates a strong student community. City centre is compact and walkable. More affordable than Dublin with an improving quality of life.",
    keyEmployers: ["Regeneron", "Stryker", "Cook Medical", "Analog Devices", "Zimmer Biomet"],
    whyRelocate: "Regeneron alone makes Limerick a top-tier biologics destination for US861 graduates. The hub is growing rapidly — a placement now positions you for permanent roles as the cluster expands."
  },
  {
    id: "cork",
    name: "Cork",
    centLat: 51.900, centLng: -8.350,
    radiusKm: 35,
    color: "#CC0000",
    tagline: "Ireland's pharmaceutical powerhouse — 7 top-10 global pharma companies in one region",
    description: "Cork city and county is home to Pfizer, Johnson & Johnson (Janssen), MSD, Eli Lilly, AbbVie, GSK, BioMarin, and Thermo Fisher — arguably the most concentrated pharmaceutical manufacturing cluster in the world. Cork is Ireland's second city, a university town with excellent quality of life, good food culture, and a strong local pharma social scene.",
    costOfLiving: 4,
    studentCommunity: "University College Cork (UCC) and Munster Technological University (MTU) create a large, active student community. Cork has a renowned food and culture scene. Very popular relocation destination.",
    keyEmployers: ["Pfizer Cork", "Johnson & Johnson (Janssen)", "Eli Lilly", "AbbVie", "BioMarin", "GSK", "Thermo Fisher"],
    whyRelocate: "Nowhere else in Ireland (or arguably Europe) has such a density of top-10 pharma companies. A Cork placement opens doors across the entire cluster — a pharma career started in Cork has lifelong network benefits."
  },
  {
    id: "waterford",
    name: "Waterford",
    centLat: 52.255, centLng: -7.100,
    radiusKm: 25,
    color: "#6B3FA0",
    tagline: "Ireland's south-east life sciences corridor — rare disease biologics and ophthalmic devices",
    description: "Waterford city and county hosts a focused cluster of life sciences companies including Bausch + Lomb (70+ year presence), Sanofi/Genzyme (rare disease biologics), and GSK Dungarvan. Waterford Institute of Technology (South East Technological University) creates strong local academic ties. A quieter, more affordable alternative to Cork or Dublin.",
    costOfLiving: 3,
    studentCommunity: "South East Technological University (SETU) campus. More relaxed pace than Dublin or Cork. Affordable and improving city with good road and rail connections.",
    keyEmployers: ["Bausch + Lomb", "Sanofi / Genzyme", "GSK Dungarvan"],
    whyRelocate: "Waterford offers rarer biologics experience (Genzyme) in a less competitive placement market. Good for students who want a more specialised, less competitive environment to develop."
  },
  {
    id: "other",
    name: "Other / Regional",
    centLat: 53.800, centLng: -8.500,
    radiusKm: 0,
    color: "#555555",
    tagline: "Regional gems — Sligo (direct train!), Mayo, and Connacht",
    description: "Several strong employers are located outside the main hubs. Abbott Sligo is notable as one of Ireland's largest medtech employers — and is on the direct Mullingar–Sligo rail line, making it uniquely accessible without a car. Hollister (Ballyhaunis, Mayo) and Chanelle Pharma (Loughrea, Galway) offer alternative routes.",
    costOfLiving: 2,
    studentCommunity: "Sligo has IT Sligo (Atlantic Technological University Sligo) creating a modest student community. Affordable, good quality of life in a less urban setting.",
    keyEmployers: ["Abbott (Sligo)", "Hollister (Ballyhaunis)", "Chanelle Pharma (Loughrea)"],
    whyRelocate: "Abbott Sligo stands out as the only major employer reachable by direct train from Mullingar without going via Dublin. For students without a car, Sligo is uniquely attractive."
  }
];

// ─── JOB RESOURCES ────────────────────────────────────────────────────────────
const JOB_RESOURCES = [
  {
    category: "Irish Life Sciences Job Boards",
    links: [
      { name: "IDA Ireland — Life Sciences", desc: "Official investment agency — sector overview and company directory for pharma, medtech, and biotech in Ireland", url: "https://www.idaireland.com/explore-your-sector/business-sectors/medtech" },
      { name: "BioPharmaChem Ireland", desc: "Industry body for biopharma and chemical/pharma — career resources, events, member company directory", url: "https://www.biopharmachemireland.ie/" },
      { name: "MedTech Ireland (formerly IBEC MedTech)", desc: "Industry body for medical technology companies in Ireland — news, events, member directory", url: "https://medtechireland.ie/" },
      { name: "Jobs.ie — Life Sciences", desc: "General Irish jobs board with strong life sciences listings", url: "https://www.jobs.ie/jobs/life-science/" },
      { name: "IrishJobs.ie — Science & Pharma", desc: "Major Irish jobs board — filter by science, pharmaceutical, medical device", url: "https://www.irishjobs.ie/jobs/pharmaceutical/" },
      { name: "LinkedIn Jobs Ireland", desc: "Most active platform for Irish pharma/biotech — set up job alerts for 'placement student Ireland'", url: "https://www.linkedin.com/jobs/search/?location=Ireland" }
    ]
  },
  {
    category: "Graduate & Placement Programmes",
    links: [
      { name: "GradIreland — Science & Pharma", desc: "Ireland's premier graduate careers portal — placement and graduate programme listings by sector", url: "https://gradireland.com/careers-advice/job-sectors/science" },
      { name: "Pfizer Ireland Graduate Programme", desc: "23-month Pfizer graduate programme — apply October/November each year", url: "https://www.pfizer.ie/career/graduate-programme/" },
      { name: "MSD Ireland Student & Graduate Opportunities", desc: "MSD Ireland early talent — applications open September annually", url: "https://jobs.msd.com/gb/en/ireland-student-opportunities" },
      { name: "ICON Plc Careers", desc: "ICON's large graduate and placement programme — one of the most accessible for Irish science graduates", url: "https://www.iconplc.com/careers/" },
      { name: "J&J Ireland Early Talent", desc: "Johnson & Johnson Ireland graduate and placement opportunities", url: "https://jobs.jnj.com/en/regions/europe/ireland" },
      { name: "AstraZeneca Early Talent (incl. Alexion)", desc: "AstraZeneca/Alexion Ireland internships and graduate schemes", url: "https://careers.astrazeneca.com/early-talent" }
    ]
  },
  {
    category: "University Placement Support",
    links: [
      { name: "TUS Midlands Careers & Placement Office", desc: "Your own university's placement office — primary contact for industrial placement year support for US861", url: "https://www.tus.ie/student-experience/careers/" },
      { name: "TUS Biotechnology (US861) Course Page", desc: "Official course page for BSc Biotechnology — placement module details and employer contacts", url: "https://tus.ie/courses/us861/" }
    ]
  },
  {
    category: "Sector Intelligence & Company Research",
    links: [
      { name: "Irish Pharma — Industry Body", desc: "Pharmaceutical industry association for Ireland — member directory, annual reports, sector statistics", url: "https://irishpharma.ie/" },
      { name: "GetReskilled — Top Pharma Companies in Ireland", desc: "Overview of top 10 pharma companies in Ireland with employment figures and site locations", url: "https://www.getreskilled.com/top-10-pharma-and-med-device-companies-in-ireland/" },
      { name: "Glassdoor Ireland — Life Sciences", desc: "Employer reviews, interview tips, and salary benchmarks from placement students and graduates", url: "https://www.glassdoor.ie/Job/ireland-life-sciences-jobs-SRCH_IL.0,7_IN155_KO8,21.htm" },
      { name: "Science Foundation Ireland", desc: "SFI funds university-industry research partnerships — good for identifying emerging Irish biotech spinouts", url: "https://www.sfi.ie/" },
      { name: "Midlands Ireland — Life Sciences", desc: "Regional development body highlighting life science employers in the Midlands (including Athlone/Westmeath)", url: "https://www.midlandsireland.ie/business/life-sciences/" }
    ]
  },
  {
    category: "Career Development for Biotech Students",
    links: [
      { name: "BioPharmaChem Ireland — Careers Resources", desc: "Sector-specific career guidance for Irish biopharma and chemistry students", url: "https://www.biopharmachemireland.ie/careers" },
      { name: "GradIreland Life Sciences Guide", desc: "Free PDF career guide for science graduates in Ireland — placement tips, CV advice, interview preparation", url: "https://gradireland.com/careers-advice/job-sectors/science" },
      { name: "Transport for Ireland Journey Planner", desc: "Plan public transport routes from Mullingar to any company location in Ireland", url: "https://www.transportforireland.ie/plan-a-journey/" }
    ]
  }
];
